CREATE DATABASE IF NOT EXISTS filmes;
USE filmes;

CREATE TABLE IF NOT EXISTS Endereco(
Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
RUA TEXT NOT NULL,
Numero INT NOT NULL,
Cidade VARCHAR(100) NOT NULL,
ESTADO VARCHAR(100) NOT NULL,
CEP VARCHAR(8) NOT NULL
);

CREATE TABLE IF NOT EXISTS Usuario(
Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL UNIQUE,
CPF VARCHAR(11) UNIQUE NOT NULL,
Endereco INT NOT NULL,
FOREIGN KEY (Endereco)
REFERENCES Endereco (Id)
);

CREATE TABLE IF NOT EXISTS Estudio(
Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Conteudo(
Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Titulo VARCHAR(100) NOT NULL,
Genero VARCHAR(100) NOT NULL,
Ano YEAR NOT NULL,
Estudio INT NOT NULL,
FOREIGN KEY (Estudio)
REFERENCES Estudio (Id)
);

CREATE TABLE IF NOT EXISTS Visualizacao(
Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Usuario INT NOT NULL,
Conteudo INT NOT NULL,
Tempo_de_visualizacao INT NOT NULL,
FOREIGN KEY (Usuario)
REFERENCES Usuario (Id),
FOREIGN KEY (Conteudo)
REFERENCES Conteudo (Id)
);
